<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Job;
use Doctrine\ORM\EntityRepository;

/**
 * JobNoteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class JobNoteRepository extends EntityRepository
{
    public function findAllRecentNotesForJob(Job $job) {
        return $this->createQueryBuilder('job_note')
            ->andWhere('job_note.job = :job')
            ->setParameter('job', $job)
            ->andWhere('job_note.createdAt > :recentDate')
            ->setParameter('recentDate', new \DateTime('-3 months'))
            ->getQuery()
            ->execute();
    }
}
